name: horse_fit
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  logger: ^2.4.0
  flutter_native_splash: ^2.4.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  cached_network_image: ^3.4.1
  skeletonizer: ^1.4.2
  connectivity_plus: ^6.0.5
  get_it: ^7.7.0
  permission_handler: ^11.3.1
  infinite_scroll_pagination: ^4.0.0
  grouped_list: ^6.0.0
  timeago: ^3.7.0
  flutter_slidable: ^3.1.1
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  #! TODO: Remove this if not needed
  uuid:

  # State Management
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4

  # Http Request
  json_annotation: ^4.9.0
  dio: ^5.7.0
  retrofit: ^4.4.0

  # Firebase

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/place_holder/
    - assets/svgs/
